[project]
name = "bank-of-canada"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "httpx",
    "pyarrow",
    "boto3",
    "backoff",
    "ratelimit",
    "duckdb",
    "deltalake>=1.3.1",
    "psutil>=7.2.1",
    "tqdm",
]
